FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY app.py .
CMD ["python3", "./app.py"]
# Add a requirements.txt file with dependencies:
# Example:
# requests==2.28.1
# flask==2.2.3